1. importation du numpy

In [4]:
import numpy as np


afficher la version de numpy 


In [5]:
np.__version__

'1.26.4'

2. déclaration d'un scalaire 

In [6]:
scalaire = np.array(50)
scalaire

array(50)

3. déclaration d'un tableau a 1 dimension 


In [10]:
vecteur = np.array([1,2,3])
vecteur

array([1, 2, 3])

4. déclaration d'un tableau a 2 dimension

In [13]:
matrice = np.array([[1,2,3],[4,5,6]])
matrice

array([[1, 2, 3],
       [4, 5, 6]])

5. Affichage d'un scalaire , vecteur et liste

In [14]:
print (scalaire)
print (vecteur)
print (matrice)

50
[1 2 3]
[[1 2 3]
 [4 5 6]]


6.Connaître les dimensions de n'importe quelle valeur 

In [7]:
scalaire.shape


()

In [17]:
vecteur.shape

(3,)

In [18]:
matrice.shape

(2, 3)

7. l'opérateur somme (permet de concatiner 2 listes et additioner 2 scalaires) 


In [26]:
liste1 = [1,2,3]
liste2 = [4,5,6]
liste1 + liste2

[1, 2, 3, 4, 5, 6]

8. pour faire la somme du contenu des deux listes on fait :

In [27]:
liste1 = np.array([1,2,3])
liste2 = np.array([4,5,6])
somme_liste = liste1 + liste2
print (liste1, "+" ,liste2 ,"=" ,somme_liste)

[1 2 3] + [4 5 6] = [5 7 9]


9. comment appliquer une fonction mathématique sur une liste 


In [30]:
from math import log 
listee=np.array ([1,2,3,4])
np.log(listee)

array([0.        , 0.69314718, 1.09861229, 1.38629436])