In [10]:
import numpy as np 


récupération d'une valeur déterminé d'une matrice 

In [11]:
matrice = np.array ( [[1,2,3,4,5,],[6,7,8,9,10],[11,12,13,14,15]])
print (matrice)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [12]:
matrice[0]

array([1, 2, 3, 4, 5])

In [13]:
matrice [0,1]

2

afficher une colonne 

In [14]:
quatrieme_colonne = matrice[:, 3]
print(quatrieme_colonne)

[ 4  9 14]


récupérer les 2émes et 3émes colonnes de toutes les lignes 


In [15]:
matrice [:,2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])

Changer les valeurs de la quatrième colonne en None
Afficher la matrice modifiée

In [18]:
matrice[:, 2] = np.nan
print(matrice)

ValueError: cannot convert float NaN to integer

In [20]:
matrix = [
    ['a', 'b', 'c', 'd', 'e'],
    ['f', 'g', 'h', 'i', 'j'],
    ['k', 'l', 'm', 'n', 'o']
]

In [23]:
for row in matrix:
    row[2] = None

# Afficher la matrice modifiée
for row in matrix:
    print(row)

['a', 'b', None, 'd', 'e']
['f', 'g', None, 'i', 'j']
['k', 'l', None, 'n', 'o']


In [24]:
matrice = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

# Calculer la moyenne de la troisième colonne

In [26]:

moyenne_colonne_3 = np.mean(matrice[:, 2])

# Remplacer les valeurs de la troisième colonne par la moyenne
matrice[:, 2] = moyenne_colonne_3

print(matrice)



[[ 1  2 13  4  5]
 [ 6  7 13  9 10]
 [11 12 13 14 15]
 [16 17 13 19 20]
 [21 22 13 24 25]]
